name: Download LW-DETR Model

on:
  workflow_dispatch:

jobs:
  download-model:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download model from Hugging Face
        run: |
          mkdir -p output
          curl -L -o output/LWDETR_small_60e_coco.pth \
            -H "User-Agent: Mozilla/5.0" \
            https://huggingface.co/xbsu/LW-DETR/resolve/main/pretrain_weights/LWDETR_small_60e_coco.pth

      - name: Upload model as artifact
        uses: actions/upload-artifact@v4
        with:
          name: lwdetr-small-model
          path: output/LWDETR_small_60e_coco.pth

      - name: Upload to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: output
          server-dir: ${{ secrets.FTP_REMOTE_DIR }}